codecov:
  token: "afe4711e-0d63-47f7-b635-d9144f8fbc90"
  bot: "codecov-io"
  ci:
    - "circleci.com"
  strict_yaml_branch: "yaml-config"
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2
    wait_for_ci: yes
  ignore:
    - "<exclude>src/main/java/ar/com/zsoft/client/api/ClientApiApplication.class"
    - "src/main/java/ar/com/zsoft/client/api/entity/*.class"